version: "3.3"
services:
  5m1e_nginx_web:
    image: nginx:alpine
    container_name: 5m1e_nginx_web
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 5m1e_web
      - 5m1e_fastapi
  5m1e_web:
    build: ./next-app
    container_name: 5m1e_web
    ports:
      - "3000:3000"
    volumes:
      - ./next-app/:/usr/app/
      # - ./next-app/packages.json:/usr/app/packages.json
      - dependencies:/usr/app/node_modules
  5m1e_fastapi:
    build: ./fastapi-app
    container_name: 5m1e_fastapi
    ports: 
      - "8888:8888"
    volumes:
      - ./fastapi-app/app/:/code/app/
      - ./fastapi-app/:/code/
      - ./fastapi-app/requirements.txt:/code/requirements.txt
      # - fastapi_packages:/usr/local/lib/python3.10/site-packages
volumes:
  dependencies:
  fastapi_packages: